apiVersion: v1
kind: ConfigMap
metadata:
  name: careeros-api-config
  namespace: careeros-api
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: "jdbc:postgresql://postgres-service:5432/careeros"
  DB_NAME: "careeros"
  REDIS_HOST: "redis-service"
  RABBITMQ_HOST: "rabbitmq-service"
  MINIO_URL: "http://minio-service:9000"