apiVersion: v1
kind: Secret
metadata:
  name: careeros-api-secrets
  namespace: careeros-api
type: Opaque
stringData:
  DB_USER: careeros
  DB_PASSWORD: careeros
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin